classes:
  concrete: 1
  grass: 0
input_config:
  classes: []
  image_size: !!python/tuple
  - 640
  - 480
  n_slices: 2
  n_slices_h: 8
  n_slices_v: 6
  ratio: !!python/tuple
  - 4
  - 3
  slice_height: 80
  slice_width: 80
