input_config:
  classes:
  - concrete
  - grass
  image_size: !!python/tuple
  - 640
  - 480
  n_slices: 5
  n_slices_h: 15
  n_slices_v: 20
  ratio: !!python/tuple
  - 4
  - 3
  slice_height: 32
  slice_width: 32
